<?php

use Illuminate\Database\Seeder;

class ComunaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('comuna')->insert([
          array('des_comu' => 'ARICA' , 'region_id' => '1'),
          array('des_comu' => 'CAMARONES' , 'region_id' => '1'),
          array('des_comu' => 'GENERAL LAGOS' , 'region_id' => '1'),
          array('des_comu' => 'PUTRE' , 'region_id' => '1'),
          
          array('des_comu' => 'ALTO HOSPICIO' , 'region_id' => '2'),
          array('des_comu' => 'CAMIÑA' , 'region_id' => '2'),
          array('des_comu' => 'COLCHANE' , 'region_id' => '2'),
          array('des_comu' => 'HUARA' , 'region_id' => '2'),
          array('des_comu' => 'IQUIQUE' , 'region_id' => '2'),
          array('des_comu' => 'PICA' , 'region_id' => '2'),
          array('des_comu' => 'POZO ALMONTE' , 'region_id' => '2'),
          
          array('des_comu' => 'ANTOFAGASTA' , 'region_id' => '3'),
          array('des_comu' => 'CALAMA' , 'region_id' => '3'),
          array('des_comu' => 'MARÍA ELENA' , 'region_id' => '3'),
          array('des_comu' => 'MEJILLONES' , 'region_id' => '3'),
          array('des_comu' => 'OLLAGÜE' , 'region_id' => '3'),
          array('des_comu' => 'SAN PEDRO DE ATACAMA' , 'region_id' => '3'),
          array('des_comu' => 'SIERRA GORDA' , 'region_id' => '3'),
          array('des_comu' => 'TALTAL' , 'region_id' => '3'),
          array('des_comu' => 'TOCOPILLA' , 'region_id' => '3'),
          
          array('des_comu' => 'ALTO DEL CARMEN' , 'region_id' => '4'),
          array('des_comu' => 'CALDERA' , 'region_id' => '4'),
          array('des_comu' => 'CHAÑARAL' , 'region_id' => '4'),
          array('des_comu' => 'COPIAPÓ' , 'region_id' => '4'),
          array('des_comu' => 'DIEGO DE ALMAGRO' , 'region_id' => '4'),
          array('des_comu' => 'FREIRINA' , 'region_id' => '4'),
          array('des_comu' => 'HUASCO' , 'region_id' => '4'),
          array('des_comu' => 'TIERRA AMARILLA' , 'region_id' => '4'),
          array('des_comu' => 'VALLENAR' , 'region_id' => '4'),
          
          array('des_comu' => 'ANDACOLLO' , 'region_id' => '5'),
          array('des_comu' => 'CANELA' , 'region_id' => '5'),
          array('des_comu' => 'COMBARBALÁ' , 'region_id' => '5'),
          array('des_comu' => 'COQUIMBO' , 'region_id' => '5'),
          array('des_comu' => 'ILLAPEL' , 'region_id' => '5'),
          array('des_comu' => 'LA HIGUERA' , 'region_id' => '5'),
          array('des_comu' => 'LA SERENA' , 'region_id' => '5'),
          array('des_comu' => 'LOS VILOS' , 'region_id' => '5'),
          array('des_comu' => 'MONTE PATRIA' , 'region_id' => '5'),
          array('des_comu' => 'OVALLE' , 'region_id' => '5'),
          array('des_comu' => 'PAIGUANO' , 'region_id' => '5'),
          array('des_comu' => 'PUNITAQUI' , 'region_id' => '5'),
          array('des_comu' => 'RÍO HURTADO' , 'region_id' => '5'),
          array('des_comu' => 'SALAMANCA' , 'region_id' => '5'),
          array('des_comu' => 'VICUÑA' , 'region_id' => '5'),
          
          array('des_comu' => 'ALGARROBO' , 'region_id' => '6'),
          array('des_comu' => 'CABILDO' , 'region_id' => '6'),
          array('des_comu' => 'CALERA' , 'region_id' => '6'),
          array('des_comu' => 'CALLE LARGA' , 'region_id' => '6'),
          array('des_comu' => 'CARTAGENA' , 'region_id' => '6'),
          array('des_comu' => 'CASABLANCA' , 'region_id' => '6'),
          array('des_comu' => 'CATEMU' , 'region_id' => '6'),
          array('des_comu' => 'CONCÓN' , 'region_id' => '6'),
          array('des_comu' => 'EL QUISCO' , 'region_id' => '6'),
          array('des_comu' => 'EL TABO' , 'region_id' => '6'),
          array('des_comu' => 'HIJUELAS' , 'region_id' => '6'),
          array('des_comu' => 'ISLA DE PASCUA' , 'region_id' => '6'),
          array('des_comu' => 'JUAN FERNÁNDEZ' , 'region_id' => '6'),
          array('des_comu' => 'LA CRUZ' , 'region_id' => '6'),
          array('des_comu' => 'LA LIGUA' , 'region_id' => '6'),
          array('des_comu' => 'LIMACHE' , 'region_id' => '6'),
          array('des_comu' => 'LLAILLAY' , 'region_id' => '6'),
          array('des_comu' => 'LOS ANDES' , 'region_id' => '6'),
          array('des_comu' => 'NOGALES' , 'region_id' => '6'),
          array('des_comu' => 'OLMUÉ' , 'region_id' => '6'),
          array('des_comu' => 'PANQUEHUE' , 'region_id' => '6'),
          array('des_comu' => 'PAPUDO' , 'region_id' => '6'),
          array('des_comu' => 'PETORCA' , 'region_id' => '6'),
          array('des_comu' => 'PUCHUNCAVÍ' , 'region_id' => '6'),
          array('des_comu' => 'PUTAENDO' , 'region_id' => '6'),
          array('des_comu' => 'QUILLOTA' , 'region_id' => '6'),
          array('des_comu' => 'QUILPUÉ' , 'region_id' => '6'),
          array('des_comu' => 'QUINTERO' , 'region_id' => '6'),
          array('des_comu' => 'RINCONADA' , 'region_id' => '6'),
          array('des_comu' => 'SAN ANTONIO' , 'region_id' => '6'),
          array('des_comu' => 'SAN ESTEBAN' , 'region_id' => '6'),
          array('des_comu' => 'SAN FELIPE' , 'region_id' => '6'),
          array('des_comu' => 'SANTA MARÍA' , 'region_id' => '6'),
          array('des_comu' => 'SANTO DOMINGO' , 'region_id' => '6'),
          array('des_comu' => 'VALPARAÍSO' , 'region_id' => '6'),
          array('des_comu' => 'VILLA ALEMANA' , 'region_id' => '6'),
          array('des_comu' => 'VIÑA DEL MAR' , 'region_id' => '6'),
          array('des_comu' => 'ZAPALLAR' , 'region_id' => '6'),
          
          array('des_comu' => 'CHÉPICA' , 'region_id' => '7'),
          array('des_comu' => 'CHIMBARONGO' , 'region_id' => '7'),
          array('des_comu' => 'CODEGUA' , 'region_id' => '7'),
          array('des_comu' => 'COINCO' , 'region_id' => '7'),
          array('des_comu' => 'COLTAUCO' , 'region_id' => '7'),
          array('des_comu' => 'DOÑIHUE' , 'region_id' => '7'),
          array('des_comu' => 'GRANEROS' , 'region_id' => '7'),
          array('des_comu' => 'LA ESTRELLA' , 'region_id' => '7'),
          array('des_comu' => 'LAS CABRAS' , 'region_id' => '7'),
          array('des_comu' => 'LITUECHE' , 'region_id' => '7'),
          array('des_comu' => 'LOLOL' , 'region_id' => '7'),
          array('des_comu' => 'MACHALÍ' , 'region_id' => '7'),
          array('des_comu' => 'MALLOA' , 'region_id' => '7'),
          array('des_comu' => 'MARCHIHUE' , 'region_id' => '7'),
          array('des_comu' => 'MOSTAZAL' , 'region_id' => '7'),
          array('des_comu' => 'NANCAGUA' , 'region_id' => '7'),
          array('des_comu' => 'NAVIDAD' , 'region_id' => '7'),
          array('des_comu' => 'OLIVAR' , 'region_id' => '7'),
          array('des_comu' => 'PALMILLA' , 'region_id' => '7'),
          array('des_comu' => 'PAREDONES' , 'region_id' => '7'),
          array('des_comu' => 'PERALILLO' , 'region_id' => '7'),
          array('des_comu' => 'PEUMO' , 'region_id' => '7'),
          array('des_comu' => 'PICHIDEGUA' , 'region_id' => '7'),
          array('des_comu' => 'PICHILEMU' , 'region_id' => '7'),
          array('des_comu' => 'PLACILLA' , 'region_id' => '7'),
          array('des_comu' => 'PUMANQUE' , 'region_id' => '7'),
          array('des_comu' => 'QUINTA DE TILCOCO' , 'region_id' => '7'),
          array('des_comu' => 'RANCAGUA' , 'region_id' => '7'),
          array('des_comu' => 'RENGO' , 'region_id' => '7'),
          array('des_comu' => 'REQUÍNOA' , 'region_id' => '7'),
          array('des_comu' => 'SAN FERNANDO' , 'region_id' => '7'),
          array('des_comu' => 'SAN VICENTE' , 'region_id' => '7'),
          array('des_comu' => 'SANTA CRUZ' , 'region_id' => '7'),
          
          array('des_comu' => 'CAUQUENES' , 'region_id' => '8'),
          array('des_comu' => 'CHANCO' , 'region_id' => '8'),
          array('des_comu' => 'COLBÚN' , 'region_id' => '8'),
          array('des_comu' => 'CONSTITUCIÓN' , 'region_id' => '8'),
          array('des_comu' => 'CUREPTO' , 'region_id' => '8'),
          array('des_comu' => 'CURICÓ' , 'region_id' => '8'),
          array('des_comu' => 'EMPEDRADO' , 'region_id' => '8'),
          array('des_comu' => 'HUALAÑÉ' , 'region_id' => '8'),
          array('des_comu' => 'LICANTÉN' , 'region_id' => '8'),
          array('des_comu' => 'LINARES' , 'region_id' => '8'),
          array('des_comu' => 'LONGAVÍ' , 'region_id' => '8'),
          array('des_comu' => 'MAULE' , 'region_id' => '8'),
          array('des_comu' => 'MOLINA' , 'region_id' => '8'),
          array('des_comu' => 'PARRAL' , 'region_id' => '8'),
          array('des_comu' => 'PELARCO' , 'region_id' => '8'),
          array('des_comu' => 'PELLUHUE' , 'region_id' => '8'),
          array('des_comu' => 'PENCAHUE' , 'region_id' => '8'),
          array('des_comu' => 'RAUCO' , 'region_id' => '8'),
          array('des_comu' => 'RETIRO' , 'region_id' => '8'),
          array('des_comu' => 'RÍO CLARO' , 'region_id' => '8'),
          array('des_comu' => 'ROMERAL' , 'region_id' => '8'),
          array('des_comu' => 'SAGRADA FAMILIA' , 'region_id' => '8'),
          array('des_comu' => 'SAN CLEMENTE' , 'region_id' => '8'),
          array('des_comu' => 'SAN JAVIER' , 'region_id' => '8'),
          array('des_comu' => 'SAN RAFAEL' , 'region_id' => '8'),
          array('des_comu' => 'TALCA' , 'region_id' => '8'),
          array('des_comu' => 'TENO' , 'region_id' => '8'),
          array('des_comu' => 'VICHUQUÉN' , 'region_id' => '8'),
          array('des_comu' => 'VILLA ALEGRE' , 'region_id' => '8'),
          array('des_comu' => 'YERBAS BUENAS' , 'region_id' => '8'),
          
          array('des_comu' => 'ALTO BIOBÍO' , 'region_id' => '9'),
          array('des_comu' => 'ANTUCO' , 'region_id' => '9'),
          array('des_comu' => 'ARAUCO' , 'region_id' => '9'),
          array('des_comu' => 'BULNES' , 'region_id' => '9'),
          array('des_comu' => 'CABRERO' , 'region_id' => '9'),
          array('des_comu' => 'CAÑETE' , 'region_id' => '9'),
          array('des_comu' => 'CHIGUAYANTE' , 'region_id' => '9'),
          array('des_comu' => 'CHILLÁN' , 'region_id' => '9'),
          array('des_comu' => 'CHILLÁN VIEJO' , 'region_id' => '9'),
          array('des_comu' => 'COBQUECURA' , 'region_id' => '9'),
          array('des_comu' => 'COELEMU' , 'region_id' => '9'),
          array('des_comu' => 'COIHUECO' , 'region_id' => '9'),
          array('des_comu' => 'CONCEPCIÓN' , 'region_id' => '9'),
          array('des_comu' => 'CONTULMO' , 'region_id' => '9'),
          array('des_comu' => 'CORONEL' , 'region_id' => '9'),
          array('des_comu' => 'CURANILAHUE' , 'region_id' => '9'),
          array('des_comu' => 'EL CARMEN' , 'region_id' => '9'),
          array('des_comu' => 'FLORIDA' , 'region_id' => '9'),
          array('des_comu' => 'HUALPÉN' , 'region_id' => '9'),
          array('des_comu' => 'HUALQUI' , 'region_id' => '9'),
          array('des_comu' => 'LAJA' , 'region_id' => '9'),
          array('des_comu' => 'LEBU' , 'region_id' => '9'),
          array('des_comu' => 'LOS ALAMOS' , 'region_id' => '9'),
          array('des_comu' => 'LOS ANGELES' , 'region_id' => '9'),
          array('des_comu' => 'LOTA' , 'region_id' => '9'),
          array('des_comu' => 'MULCHÉN' , 'region_id' => '9'),
          array('des_comu' => 'NACIMIENTO' , 'region_id' => '9'),
          array('des_comu' => 'NEGRETE' , 'region_id' => '9'),
          array('des_comu' => 'NINHUE' , 'region_id' => '9'),
          array('des_comu' => 'ÑIQUÉN' , 'region_id' => '9'),
          array('des_comu' => 'PEMUCO' , 'region_id' => '9'),
          array('des_comu' => 'PENCO' , 'region_id' => '9'),
          array('des_comu' => 'PINTO' , 'region_id' => '9'),
          array('des_comu' => 'PORTEZUELO' , 'region_id' => '9'),
          array('des_comu' => 'QUILACO' , 'region_id' => '9'),
          array('des_comu' => 'QUILLECO' , 'region_id' => '9'),
          array('des_comu' => 'QUILLÓN' , 'region_id' => '9'),
          array('des_comu' => 'QUIRIHUE' , 'region_id' => '9'),
          array('des_comu' => 'RÁNQUIL' , 'region_id' => '9'),
          array('des_comu' => 'SAN CARLOS' , 'region_id' => '9'),
          array('des_comu' => 'SAN FABIÁN' , 'region_id' => '9'),
          array('des_comu' => 'SAN IGNACIO' , 'region_id' => '9'),
          array('des_comu' => 'SAN NICOLÁS' , 'region_id' => '9'),
          array('des_comu' => 'SAN PEDRO DE LA PAZ' , 'region_id' => '9'),
          array('des_comu' => 'SAN ROSENDO' , 'region_id' => '9'),
          array('des_comu' => 'SANTA BÁRBARA' , 'region_id' => '9'),
          array('des_comu' => 'SANTA JUANA' , 'region_id' => '9'),
          array('des_comu' => 'TALCAHUANO' , 'region_id' => '9'),
          array('des_comu' => 'TIRÚA' , 'region_id' => '9'),
          array('des_comu' => 'TOMÉ' , 'region_id' => '9'),
          array('des_comu' => 'TREGUACO' , 'region_id' => '9'),
          array('des_comu' => 'TUCAPEL' , 'region_id' => '9'),
          array('des_comu' => 'YUMBEL' , 'region_id' => '9'),
          array('des_comu' => 'YUNGAY' , 'region_id' => '9'),

          array('des_comu' => 'ANGOL' , 'region_id' => '10'),
          array('des_comu' => 'CARAHUE' , 'region_id' => '10'),
          array('des_comu' => 'CHOLCHOL' , 'region_id' => '10'),
          array('des_comu' => 'COLLIPULLI' , 'region_id' => '10'),
          array('des_comu' => 'CUNCO' , 'region_id' => '10'),
          array('des_comu' => 'CURACAUTÍN' , 'region_id' => '10'),
          array('des_comu' => 'CURARREHUE' , 'region_id' => '10'),
          array('des_comu' => 'ERCILLA' , 'region_id' => '10'),
          array('des_comu' => 'FREIRE' , 'region_id' => '10'),
          array('des_comu' => 'GALVARINO' , 'region_id' => '10'),
          array('des_comu' => 'GORBEA' , 'region_id' => '10'),
          array('des_comu' => 'LAUTARO' , 'region_id' => '10'),
          array('des_comu' => 'LONCOCHE' , 'region_id' => '10'),
          array('des_comu' => 'LONQUIMAY' , 'region_id' => '10'),
          array('des_comu' => 'LOS SAUCES' , 'region_id' => '10'),
          array('des_comu' => 'LUMACO' , 'region_id' => '10'),
          array('des_comu' => 'MELIPEUCO' , 'region_id' => '10'),
          array('des_comu' => 'NUEVA IMPERIAL' , 'region_id' => '10'),
          array('des_comu' => 'PADRE LAS CASAS' , 'region_id' => '10'),
          array('des_comu' => 'PERQUENCO' , 'region_id' => '10'),
          array('des_comu' => 'PITRUFQUÉN' , 'region_id' => '10'),
          array('des_comu' => 'PUCÓN' , 'region_id' => '10'),
          array('des_comu' => 'PURÉN' , 'region_id' => '10'),
          array('des_comu' => 'RENAICO' , 'region_id' => '10'),
          array('des_comu' => 'SAAVEDRA' , 'region_id' => '10'),
          array('des_comu' => 'TEMUCO' , 'region_id' => '10'),
          array('des_comu' => 'TEODORO SCHMIDT' , 'region_id' => '10'),
          array('des_comu' => 'TOLTÉN' , 'region_id' => '10'),
          array('des_comu' => 'TRAIGUÉN' , 'region_id' => '10'),
          array('des_comu' => 'VICTORIA' , 'region_id' => '10'),
          array('des_comu' => 'VILCÚN' , 'region_id' => '10'),
          array('des_comu' => 'VILLARRICA' , 'region_id' => '10'),

          array('des_comu' => 'CORRAL' , 'region_id' => '11'),
          array('des_comu' => 'FUTRONO' , 'region_id' => '11'),
          array('des_comu' => 'LA UNIÓN' , 'region_id' => '11'),
          array('des_comu' => 'LAGO RANCO' , 'region_id' => '11'),
          array('des_comu' => 'LANCO' , 'region_id' => '11'),
          array('des_comu' => 'LOS LAGOS' , 'region_id' => '11'),
          array('des_comu' => 'MÁFIL' , 'region_id' => '11'),
          array('des_comu' => 'MARIQUINA' , 'region_id' => '11'),
          array('des_comu' => 'PAILLACO' , 'region_id' => '11'),
          array('des_comu' => 'PANGUIPULLI' , 'region_id' => '11'),
          array('des_comu' => 'RÍO BUENO' , 'region_id' => '11'),
          array('des_comu' => 'VALDIVIA' , 'region_id' => '11'),

          array('des_comu' => 'ANCUD' , 'region_id' => '12'),
          array('des_comu' => 'CALBUCO' , 'region_id' => '12'),
          array('des_comu' => 'CASTRO' , 'region_id' => '12'),
          array('des_comu' => 'CHAITÉN' , 'region_id' => '12'),
          array('des_comu' => 'CHONCHI' , 'region_id' => '12'),
          array('des_comu' => 'COCHAMÓ' , 'region_id' => '12'),
          array('des_comu' => 'CURACO DE VÉLEZ' , 'region_id' => '12'),
          array('des_comu' => 'DALCAHUE' , 'region_id' => '12'),
          array('des_comu' => 'FRESIA' , 'region_id' => '12'),
          array('des_comu' => 'FRUTILLAR' , 'region_id' => '12'),
          array('des_comu' => 'FUTALEUFÚ' , 'region_id' => '12'),
          array('des_comu' => 'HUALAIHUÉ' , 'region_id' => '12'),
          array('des_comu' => 'LLANQUIHUE' , 'region_id' => '12'),
          array('des_comu' => 'LOS MUERMOS' , 'region_id' => '12'),
          array('des_comu' => 'MAULLÍN' , 'region_id' => '12'),
          array('des_comu' => 'OSORNO' , 'region_id' => '12'),
          array('des_comu' => 'PALENA' , 'region_id' => '12'),
          array('des_comu' => 'PUERTO MONTT' , 'region_id' => '12'),
          array('des_comu' => 'PUERTO OCTAY' , 'region_id' => '12'),
          array('des_comu' => 'PUERTO VARAS' , 'region_id' => '12'),
          array('des_comu' => 'PUQUELDÓN' , 'region_id' => '12'),
          array('des_comu' => 'PURRANQUE' , 'region_id' => '12'),
          array('des_comu' => 'PUYEHUE' , 'region_id' => '12'),
          array('des_comu' => 'QUEILÉN' , 'region_id' => '12'),
          array('des_comu' => 'QUELLÓN' , 'region_id' => '12'),
          array('des_comu' => 'QUEMCHI' , 'region_id' => '12'),
          array('des_comu' => 'QUINCHAO' , 'region_id' => '12'),
          array('des_comu' => 'RÍO NEGRO' , 'region_id' => '12'),
          array('des_comu' => 'SAN JUAN DE LA COSTA' , 'region_id' => '12'),
          array('des_comu' => 'SAN PABLO' , 'region_id' => '12'),

          array('des_comu' => 'AISÉN' , 'region_id' => '13'),
          array('des_comu' => 'CHILE CHICO' , 'region_id' => '13'),
          array('des_comu' => 'CISNES' , 'region_id' => '13'),
          array('des_comu' => 'COCHRANE' , 'region_id' => '13'),
          array('des_comu' => 'COIHAIQUE' , 'region_id' => '13'),
          array('des_comu' => 'GUAITECAS' , 'region_id' => '13'),
          array('des_comu' => 'LAGO VERDE' , 'region_id' => '13'),
          array('des_comu' => 'O´HIGGINS' , 'region_id' => '13'),
          array('des_comu' => 'RÍO IBÁÑEZ' , 'region_id' => '13'),
          array('des_comu' => 'TORTEL' , 'region_id' => '13'),

          array('des_comu' => 'ANTÁRTICA' , 'region_id' => '14'),
          array('des_comu' => 'CABO DE HORNOS (EX-NAVARINO)' , 'region_id' => '14'),
          array('des_comu' => 'LAGUNA BLANCA' , 'region_id' => '14'),
          array('des_comu' => 'NATALES' , 'region_id' => '14'),
          array('des_comu' => 'PORVENIR' , 'region_id' => '14'),
          array('des_comu' => 'PRIMAVERA' , 'region_id' => '14'),
          array('des_comu' => 'PUNTA ARENAS' , 'region_id' => '14'),
          array('des_comu' => 'RÍO VERDE' , 'region_id' => '14'),
          array('des_comu' => 'SAN GREGORIO' , 'region_id' => '14'),
          array('des_comu' => 'TIMAUKEL' , 'region_id' => '14'),
          array('des_comu' => 'TORRES DEL PAINE' , 'region_id' => '14'),

          array('des_comu' => 'ALHUÉ' , 'region_id' => '15'),
          array('des_comu' => 'BUIN' , 'region_id' => '15'),
          array('des_comu' => 'CALERA DE TANGO' , 'region_id' => '15'),
          array('des_comu' => 'CERRILLOS' , 'region_id' => '15'),
          array('des_comu' => 'CERRO NAVIA' , 'region_id' => '15'),
          array('des_comu' => 'COLINA' , 'region_id' => '15'),
          array('des_comu' => 'CONCHALÍ' , 'region_id' => '15'),
          array('des_comu' => 'CURACAVÍ' , 'region_id' => '15'),
          array('des_comu' => 'EL BOSQUE' , 'region_id' => '15'),
          array('des_comu' => 'EL MONTE' , 'region_id' => '15'),
          array('des_comu' => 'ESTACIÓN CENTRAL' , 'region_id' => '15'),
          array('des_comu' => 'HUECHURABA' , 'region_id' => '15'),
          array('des_comu' => 'INDEPENDENCIA' , 'region_id' => '15'),
          array('des_comu' => 'ISLA DE MAIPO' , 'region_id' => '15'),
          array('des_comu' => 'LA CISTERNA' , 'region_id' => '15'),
          array('des_comu' => 'LA FLORIDA' , 'region_id' => '15'),
          array('des_comu' => 'LA GRANJA' , 'region_id' => '15'),
          array('des_comu' => 'LA PINTANA' , 'region_id' => '15'),
          array('des_comu' => 'LA REINA' , 'region_id' => '15'),
          array('des_comu' => 'LAMPA' , 'region_id' => '15'),
          array('des_comu' => 'LAS CONDES' , 'region_id' => '15'),
          array('des_comu' => 'LO BARNECHEA' , 'region_id' => '15'),
          array('des_comu' => 'LO ESPEJO' , 'region_id' => '15'),
          array('des_comu' => 'LO PRADO' , 'region_id' => '15'),
          array('des_comu' => 'MACUL' , 'region_id' => '15'),
          array('des_comu' => 'MAIPÚ' , 'region_id' => '15'),
          array('des_comu' => 'MARÍA PINTO' , 'region_id' => '15'),
          array('des_comu' => 'MELIPILLA' , 'region_id' => '15'),
          array('des_comu' => 'ÑUÑOA' , 'region_id' => '15'),
          array('des_comu' => 'PADRE HURTADO' , 'region_id' => '15'),
          array('des_comu' => 'PAINE' , 'region_id' => '15'),
          array('des_comu' => 'PEDRO AGUIRRE CERDA' , 'region_id' => '15'),
          array('des_comu' => 'PEÑAFLOR' , 'region_id' => '15'),
          array('des_comu' => 'PEÑALOLÉN' , 'region_id' => '15'),
          array('des_comu' => 'PIRQUE' , 'region_id' => '15'),
          array('des_comu' => 'PROVIDENCIA' , 'region_id' => '15'),
          array('des_comu' => 'PUDAHUEL' , 'region_id' => '15'),
          array('des_comu' => 'PUENTE ALTO' , 'region_id' => '15'),
          array('des_comu' => 'QUILICURA' , 'region_id' => '15'),
          array('des_comu' => 'QUINTA NORMAL' , 'region_id' => '15'),
          array('des_comu' => 'RECOLETA' , 'region_id' => '15'),
          array('des_comu' => 'RENCA' , 'region_id' => '15'),
          array('des_comu' => 'SAN BERNARDO' , 'region_id' => '15'),
          array('des_comu' => 'SAN JOAQUÍN' , 'region_id' => '15'),
          array('des_comu' => 'SAN JOSÉ DE MAIPO' , 'region_id' => '15'),
          array('des_comu' => 'SAN MIGUEL' , 'region_id' => '15'),
          array('des_comu' => 'SAN PEDRO' , 'region_id' => '15'),
          array('des_comu' => 'SAN RAMÓN' , 'region_id' => '15'),
          array('des_comu' => 'SANTIAGO' , 'region_id' => '15'),
          array('des_comu' => 'TALAGANTE' , 'region_id' => '15'),
          array('des_comu' => 'TILTIL' , 'region_id' => '15'),
          array('des_comu' => 'VITACURA' , 'region_id' => '15')
        ]);
    }
}
